#!/bin/bash -e

createXDGDesktopItem()
{
    cat <<EOF
[Desktop Entry]
Type=Application
Name=$desktopName
Exec=$exec
Categories=$categories
EOF
    if [ "$genericName" != "" ]
    then
        echo "GenericName=$genericName"
    fi

    if [ "$comment" != "" ]
    then
        echo "Comment=$comment"
    fi

    if [ "$icon" != "" ]
    then
        echo "Icon=$icon"
    fi

    if [ "$terminal" != "" ]
    then
        echo "Terminal=$terminal"
    fi

    if [ "$terminalOptions" != "" ]
    then
        echo "TerminalOptions=$terminalOptions"
    fi

    if [ "$path" != "" ]
    then
        echo "Path=$path"
    fi

    if [ "$mimeType" != "" ]
    then
        echo "MimeType=$mimeType"
    fi

    if [ "$noDisplay" != "" ]
    then
        echo "NoDisplay=$noDisplay"
    fi
}

installXDGDesktopItemsPhase()
{
    local desktopFileName="${desktopFileName:-$name}"

    mkdir -p "$desktopTargetDir"
    createXDGDesktopItem > "$desktopTargetDir/$desktopFileName.desktop"
}
